### ISSUE TITLE
Do you need stablediffusion1.5 as well as the dreambooth model installed?

### ISSUE THREAD

**Issue by G-force78** [open-mmlab/PIA#3]
I have this  error

Traceback (most recent call last):
  File "/content/PIA/inference.py", line 10, in <module>
    from animatediff.pipelines import I2VPipeline
  File "/content/PIA/animatediff/pipelines/__init__.py", line 1, in <module>
    from .i2v_pipeline import I2VPipeline
  File "/content/PIA/animatediff/pipelines/i2v_pipeline.py", line 9, in <module>
    from diffusers.configuration_utils import FrozenDict
ModuleNotFoundError: No module named 'diffusers'

**Comment by LeoXing1996** [comment]
Hey @G-force78, you need to install diffusers first. Please follow this [instruction](https://github.com/open-mmlab/PIA?tab=readme-ov-file#prepare-environment)
